matrix:
  include:
  - language: python
    name: "Bandit, Pur & Pycodestyle (Python 2.7)"
    python: 2.7
    os: linux
    before_install:
      - sudo apt-get install figlet
      - mkdir travis
      - git clone https://github.com/TravisToolbox/bandit-travis.git travis/bandit
      - git clone https://github.com/TravisToolbox/pur-travis.git travis/pur
      - git clone https://github.com/TravisToolbox/pycodestyle-travis.git travis/pycodetyle
      - pip install --upgrade setuptools
    install:
      - ./travis/bandit/install.sh
      - ./travis/pur/install.sh
      - ./travis/pycodetyle/install.sh
    script:
      - figlet -c -w 125 -f big Bandit Tests
      - ./travis/bandit/scan.sh
      - figlet -c -w 125 -f big Pur Tests
      - ./travis/pur/scan.sh
      - figlet -c -w 125 -f big Pycodestyle Tests
      - ./travis/pycodetyle/scan.sh
  - language: python
    name: "Bandit, Pur & Pycodestyle (Python 3.4)"
    python: 3.4
    os: linux
    before_install:
      - sudo apt-get install figlet
      - mkdir travis
      - git clone https://github.com/TravisToolbox/bandit-travis.git travis/bandit
      - git clone https://github.com/TravisToolbox/pur-travis.git travis/pur
      - git clone https://github.com/TravisToolbox/pycodestyle-travis.git travis/pycodetyle
      - pip install --upgrade setuptools
    install:
      - ./travis/bandit/install.sh
      - ./travis/pur/install.sh
      - ./travis/pycodetyle/install.sh
    script:
      - figlet -c -w 125 -f big Bandit Tests
      - ./travis/bandit/scan.sh
      - figlet -c -w 125 -f big Pur Tests
      - ./travis/pur/scan.sh
      - figlet -c -w 125 -f big Pycodestyle Tests
      - ./travis/pycodetyle/scan.sh
  - language: python
    name: "Bandit, Pur & Pycodestyle (Python 3.5)"
    python: 3.5
    os: linux
    before_install:
      - sudo apt-get install figlet
      - mkdir travis
      - git clone https://github.com/TravisToolbox/bandit-travis.git travis/bandit
      - git clone https://github.com/TravisToolbox/pur-travis.git travis/pur
      - git clone https://github.com/TravisToolbox/pycodestyle-travis.git travis/pycodetyle
      - pip install --upgrade setuptools
    install:
      - ./travis/bandit/install.sh
      - ./travis/pur/install.sh
      - ./travis/pycodetyle/install.sh
    script:
      - figlet -c -w 125 -f big Bandit Tests
      - ./travis/bandit/scan.sh
      - figlet -c -w 125 -f big Pur Tests
      - ./travis/pur/scan.sh
      - figlet -c -w 125 -f big Pycodestyle Tests
      - ./travis/pycodetyle/scan.sh
  - language: python
    name: "Bandit, Pur & Pycodestyle (Python 3.6)"
    python: 3.6
    os: linux
    before_install:
      - sudo apt-get install figlet
      - mkdir travis
      - git clone https://github.com/TravisToolbox/bandit-travis.git travis/bandit
      - git clone https://github.com/TravisToolbox/pur-travis.git travis/pur
      - git clone https://github.com/TravisToolbox/pycodestyle-travis.git travis/pycodetyle
      - pip install --upgrade setuptools
    install:
      - ./travis/bandit/install.sh
      - ./travis/pur/install.sh
      - ./travis/pycodetyle/install.sh
    script:
      - figlet -c -w 125 -f big Bandit Tests
      - ./travis/bandit/scan.sh
      - figlet -c -w 125 -f big Pur Tests
      - ./travis/pur/scan.sh
      - figlet -c -w 125 -f big Pycodestyle Tests
      - ./travis/pycodetyle/scan.sh
  - language: ruby
    name: "Link Checker (rvm 2.6.1)"
    rvm: 2.6.1
    before_install:
      - mkdir travis
      - git clone https://github.com/TravisToolbox/awesomebot-travis.git travis/awesomebot
    install:
      - ./travis/awesomebot/install.sh
    script:
      - ./travis/awesomebot/scan.sh
notifications:
  email: false
  slack:
    secure: sF6GKC+rbvWXpEnt2Ww+74BJinX6OPhWdAOWyrrMm5lvIoIpm4bp6L1EqWwrsITR3/SSepmexuvIR3tHDXmallNfMHA7CJl+nBPyOAI+s5jYGZ5mrPoDEc/w4c57yHxx6oYa28SXwAnx/bghCaDRuEQzqj/Ah/DTjiAQX7ofKzInl4pcaTVyX+J1JasPIrBbTAOw/mxHAy3E+alaFoonJscpMTtAyqRIye5EELy3VhAFAbe5VwvZwN1IamzoWnUC/j/6z9KJJG4qE51N0mOPd/OY6snEgCkQNidkhvL+8JdL/y42WM9Vybl5YcCqBbZQcQVTfi9gVw18eg3fHE07WlAMR7W6Z9etrKSY/jnJVGcnydEvbny4OLa2xzccfHmremtvGMdR8OJCIGhprzkB79+bwdSpnIpngHflETKgw4XnhtbNHKUNf+C6lN9OjHpbEWrIAKQdbvkdEAMts02Jy4DjQ5d+hw3hnEJ1ZnEC4V2Pd29jNUy3NGST9wBOPXePafQz6oBWf/P7c19kigt5zjy+K/dnG1CFlGu7K6Od3Qp+foZj77dWq1fQLxHRMwG3dGq2DmzLajyC5scEWNXIfyz2IA1y9KqMYVU9LVdtjIj8iiffA9o219E+w5yZNMmWzR2bx3wUUiHuZBDNvqLN423sOAWXdI0NN85rq9qpyh0=
